# Generated by Django 3.2.7 on 2021-09-28 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_rename_centers_center'),
    ]

    operations = [
        migrations.AddField(
            model_name='center',
            name='center_address',
            field=models.CharField(default='', max_length=200),
        ),
    ]
